### ISSUE TITLE
Skipping tests?

### ISSUE THREAD

**Issue by iamvery** [exercism/elm#151]
Would there be any interest in skipping later tests in exercises? I'm thinking something similar to `xit` used in [the Ecmascript exercises](https://github.com/exercism/ecmascript/blob/master/exercises/accumulate/accumulate.spec.js). Syntactically it would be a little more heavy-weight in Elm, so I've opted to ask in an issue before making the change for pull request.

Also related, I noticed what seems to be an error in the elm-test README about this feature. See https://github.com/elm-community/elm-test/pull/186.

**Comment by iamvery** [comment]
Also fwiw, I've just been commenting out later tests as I work through Elm exercises, but the nice thing about `skip` is that even though the code is not run, it is compiled and therefore gives you a little more information about type requirements as you're getting started. For e.g. I'm currently working on the _triangle_ exercise and with later tests commented I didn't catch that the function signature must support `Float` rather than just `Int` sides.

**Comment by tgecho** [comment]
I'm very open. The skip feature didn't exist when many of these exercises were created and I didn't think to go back and retrofit them. PR welcome!
