### ISSUE TITLE
All Your Base is missing package.json

### ISSUE THREAD

**Issue by hanjiexi** [exercism/elm#183]
Other exercises have `package.json` and work fine, but `all-your-base` is missing that file so I am unable to run install and test.

Running `npm install` in the `all-your-base` directory yields the following:
```bash
npm WARN saveError ENOENT: no such file or directory, open '/home/jhanson/Projects/exercism/elm/all-your-base/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/jhanson/Projects/exercism/elm/all-your-base/package.json'
npm WARN all-your-base No description
npm WARN all-your-base No repository field.
npm WARN all-your-base No README data
npm WARN all-your-base No license field.
```
Running `npm test` yields the following:
```bash
npm ERR! path /home/jhanson/Projects/exercism/elm/all-your-base/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/jhanson/Projects/exercism/elm/all-your-base/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by tuxagon** [comment]
@hanjiexi Nice find! Definitely will need to patch that.

**Comment by tuxagon** [comment]
@hanjiexi Per #194, it was agreed upon to actually do away with the localized `package.json` in favor of a shared one at the root to keep exercises consistent. #198 was created to fix that. I'm going to close this, but you're welcome to re-open if you think this still has some relevance. Thank you for looking out and discovering this!
