### ISSUE TITLE
New Contributor(s)

### ISSUE THREAD

**Issue by tuxagon** [exercism/elm#188]
Per this [conversation](https://github.com/exercism/discussions/issues/210#issuecomment-363379656) in [exercism/discussions](https://github.com/exercism/discussions), I am creating this issue to provide a starting point for getting at least 1 new contributor for this repo. Who? What prerequisites are there? Anyone interested? 

I would say I am interested, but I would like this to possibly provide a way for someone more qualified to volunteer. I've only submitted 1 PR here and no communication has happened, so there is a lot for me to still learn about exercism.

Ultimately, I hope this helps elm become more active and encourage more contributions, as well as, helps the current maintainers, regardless of the reasons for their hiatus. Life is crazy and we should not disparage them for not being able to be more active.

**Comment by neganp** [comment]
I would also be interested in helping out! I'm not sure what counts as qualified, but I'd happily spend a little time each week reviewing issues and PRs.

**Comment by budmc29** [comment]
@kytrinyx what do you think?

**Comment by kytrinyx** [comment]
@budmc29 Absolutely. This reminds me that I need to finish my maintainer bot that lets maintainers add new maintainers to their own repos!

@neganp @tuxagon  I've added you both to the repo. We've got some docs up about maintaining, please ask questions if you have any! https://github.com/exercism/docs/blob/master/maintaining-a-track/README.md

**Comment by kytrinyx** [comment]
I'm closing this, but if you all find more enthusiastic folks, don't hesitate to either reopen it or open a new one.

**Comment by budmc29** [comment]
Congrats.

**Comment by yurrriq** [comment]
I’m happy to help, as I’m able.

**Comment by kytrinyx** [comment]
Thanks @yurrriq! I've added you to the team.

**Comment by churchie317** [comment]
Not sure if there are too many cooks in the kitchen, but I'd like to help out as well!

**Comment by kytrinyx** [comment]
@churchie317 hardly :) Invite incoming.

Thanks, everyone, for getting involved!
