### ISSUE TITLE
Update Contributing section in README.md

### ISSUE THREAD

**Issue by churchie317** [exercism/elm#193]
Reading through the `README.md`, I wonder if there are opportunities for improvements to the Contributing section. Looking at the `git blame`, most of the work is a couple years old and, I would have to imagine, a little stale.

1. One of the big improvements that I'd like to see is the addition of sub-sections for the different kinds of contributions. Recently, I submitted a PR for a new Elm exercise and it wasn't immediately obvious what the steps for creating that exercise actually were. Currently, the Elm track has 36 exercises but I think we can improve that number by making the process for adding new exercises to the track more explicit. It would be nice if someone wanted to make a contribution, jump to their relevant section, and know immediately what they needed to do to land that contribution.

2. The process for using `configlet` is, in my opinion, a little unclear and feels somewhat tacked on. Specifically, this line: 

> If you are submitting a new exercise, be sure to add it to the appropriate place in the config.json file. Also, please run bin/fetch-configlet && bin/configlet to ensure the exercise is configured correctly.

says to run _a_ command, but doesn't really explain what that command does or then go on to say how to use `configlet`. Then again, I've never used Go before so I'm not sure if this is just me being dense.

3. This is nit-picky, but I noticed the test example doesn't leverage the skip function. Given exercism's emphasis on incremental development and TDD, providing an example doesn't seem like a bad idea.

Thoughts?

**Comment by tuxagon** [comment]
Including `skip` in the example code wouldn't be a bad idea. What is your suggestion to clearing up misunderstanding about `configlet`, though? Are those the only 2 things you believe should be more explicit?

**Comment by tuxagon** [comment]
@churchie317 what are your thoughts on this issue?

**Comment by tuxagon** [comment]
@churchie317 do you want this to stay as `wontfix`?

**Comment by mpizenberg** [comment]
Hi @churchie317, I agree that the contributing section is not very straightforward. I'm gonna do a little bit of cleaning and updating of the track, which should take roughly two weekends I hope. Let me know by then if you're still interested in making a PR for this. If I don't hear anything by then, I'll close the issue.

**Comment by mpizenberg** [comment]
Hi again @churchie317 , I've rewritten the readme as part of the update process of updating the track to elm 0.19.1. Don't hesitate to let me know if you find the new readme easier to follow. It is temporarily available in the [`readme` branch of my fork](https://github.com/mpizenberg/elm/tree/readme).
