### ISSUE TITLE
Improve Consistency Among Exercises

### ISSUE THREAD

**Issue by tuxagon** [exercism/elm#194]
I decided to take a stroll through the current exercises and found some inconsistencies when it comes to `package.json`.

First, there is a root `package.json`
```json
{
  "scripts": {
    "test": "elm-test"
  },
  "dependencies": {
    "elm": "0.18.0",
    "elm-test": "0.18.3"
  }
}
```

In *_most_ of the exercises
```json
{
    "description": "Exercism/Elm",
    "repository": "https://github.com/exercism/elm.git",
    "license": "MIT",
    "scripts": {
        "postinstall": "elm-package install -y",
        "watch": "elm-test --watch",
        "test": "elm-test"
    },
    "dependencies": {
        "elm": "0.18.0",
        "elm-test": "0.18.3"
    }
}
```

Also, as of this issue creation, none of the exercises have `package-lock.json`, which is fairly new (added in npm version `^5.x.x`).

I'm not sure what the decision behind each exercise having their own `package.json` is, but it could be removed altogether and kept only at the root level. This would help any updates be more consistent and it would mirror the same approach https://github.com/exercism/javascript does by just having a root `package.json`.

*: Non-existent in `all-your-base`

**Comment by churchie317** [comment]
So the proposal is to drop the `package.json`s for each exercise, define one at the root _and_ define a single `package-lock.json` at the root as well, correct? If so, I can probably take care of this.

**Comment by tuxagon** [comment]
@churchie317 Unless there are objections, that is what makes sense to me. The `package.json` files in each exercise feel superfluous. The `package-lock.json` file will just get created automatically for you if you clone and then `npm install` at the root of the repo.

If you are able to tackle this, let me know if you actually encounter issues. This issue was created to start the conversation and then have a clear direction moving forward so that it can be part of the PR checklist.

**Comment by churchie317** [comment]
Okay, so looking into it I suspect there's a reason each exercise includes its own `package.json` and it's related to the exercise `README` instructions. I suspect the instructions were assembled at a time before it was idiomatic to install Elm globally. Specifically, the `README` instructions are to run:

1. `npm install`. Looking at the `package.json`, we can see this means Elm is being installed for each exercise. I'd be interested to hear some thoughts, but this feels heavy-handed to me.
2. `npm test` which again is merely a wrapper for running `elm-test`.

The only nice-to-have users would lose is the test watcher, but we can tell them to simply run `elm-test --watch`. 

I remain in favor of removing the `package.json`s and updating the `README`s to instruct users to `npm install -g elm` and `npm install -g elm-test`. I think this is more in line with idiomatic Elm and makes Elm feel less coupled to the Node ecosystem, as it should as the language matures.

**Comment by neganp** [comment]
I would agree, and add that #182 is part of this.

**Comment by churchie317** [comment]
@neganp good catch, I totally would have missed that!

So it seems updating the docs will lead to a reduction in complexity and more idiomatic Elm, per #182.

**Comment by tuxagon** [comment]
#198 closes this
