### ISSUE TITLE
Improve Useful Resources

### ISSUE THREAD

**Issue by tuxagon** [exercism/elm#197]
I am working on #182 and #194 and came across the useful resources section on the website. I think this could do with some love because there have been a lot of useful resources since then. My thought is that we can use this issue to list some and why they are useful.

https://github.com/exercism/elm/blob/master/docs/RESOURCES.md

I will update this comment to include the curated list for when we get to updating the document.

--- CURATED LIST ---

* Ellie: https://ellie-app.com/new (Tool)
* Daily Drip: https://www.dailydrip.com/topics/elm (Learn)
* Elm Guide: https://guide.elm-lang.org/ (Learn)
* Awesome Elm: https://github.com/isRuslan/awesome-elm (Awesome)

**Comment by tuxagon** [comment]
Obviously we probably don't want to just give an overwhelming list of new stuff either, so we could probably pick videos based on just `elm-conf` too, potentially. I think some of the videos in the current list still stand, like "Let's be Mainstream".

**Comment by neganp** [comment]
I would agree: that page could use some love. :+1: 

I like adding Ellie and Awesome Elm. Perhaps the [Elm Guide](https://guide.elm-lang.org/) would be a good thing to have as well?

**Comment by tuxagon** [comment]
Updated!

**Comment by neganp** [comment]
I can take care of this.
