### ISSUE TITLE
Add stubs solutions to exercise templates

### ISSUE THREAD

**Issue by neganp** [exercism/elm#206]
The Exercism docs suggest that each exercise should have a stub solution so that the example exercises compile but don't pass the tests. A good example of a track that implements this is the [C# track](https://github.com/exercism/csharp).

The Elm track should implement stub solutions in each of its exercise templates.

The stub should include a function with the name and signature expected by the tests. This might include some core module imports (e.g.  if you could solve the problem with Lists or Arrays but the tests expect Lists, the template will need to import the List module to write out the function's type signature).

The body of the stub function can be just a call to [`Debug.crash`](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Debug#crash) with a message indicating that this is where the learner should put their solution.

- [x] [accumulate](../tree/master/exercises/accumulate)
- [x] [acronym](../tree/master/exercises/acronym)
- [x] [allergies](../tree/master/exercises/allergies)
- [x] [all-your-base](../tree/master/exercises/all-your-base)
- [x] [anagram](../tree/master/exercises/anagram)
- [x] [atbash-cipher](../tree/master/exercises/atbash-cipher)
- [x] [binary-search](../tree/master/exercises/binary-search)
- [x] [bob](../tree/master/exercises/bob)
- [x] [collatz-conjecture](../tree/master/exercises/collatz-conjecture)
- [x] [difference-of-squares](../tree/master/exercises/difference-of-squares)
- [x] [etl](../tree/master/exercises/etl)
- [x] [gigasecond](../tree/master/exercises/gigasecond)
- [x] [grade-school](../tree/master/exercises/grade-school)
- [x] [grains](../tree/master/exercises/grains)
- [x] [hamming](../tree/master/exercises/hamming)
- [x] [hello-world](../tree/master/exercises/hello-world)
- [x] [isogram](../tree/master/exercises/isogram)
- [x] [largest-series-product](../tree/master/exercises/largest-series-product)
- [x] [leap](../tree/master/exercises/leap)
- [x] [list-ops](../tree/master/exercises/list-ops)
- [x] [luhn](../tree/master/exercises/luhn)
- [x] [nucleotide-count](../tree/master/exercises/nucleotide-count)
- [x] [pangram](../tree/master/exercises/pangram)
- [x] [pascals-triangle](../tree/master/exercises/pascals-triangle)
- [x] [phone-number](../tree/master/exercises/phone-number)
- [x] [raindrops](../tree/master/exercises/raindrops)
- [x] [rna-transcription](../tree/master/exercises/rna-transcription)
- [x] [robot-simulator](../tree/master/exercises/robot-simulator)
- [x] [roman-numerals](../tree/master/exercises/roman-numerals)
- [x] [run-length-encoding](../tree/master/exercises/run-length-encoding)
- [x] [say](../tree/master/exercises/say)
- [x] [scrabble-score](../tree/master/exercises/scrabble-score)
- [x] [series](../tree/master/exercises/series)
- [x] [space-age](../tree/master/exercises/space-age)
- [x] [strain](../tree/master/exercises/strain)
- [x] [sublist](../tree/master/exercises/sublist)
- [x] [sum-of-multiples](../tree/master/exercises/sum-of-multiples)
- [x] [triangle](../tree/master/exercises/triangle)
- [x] [twelve-days](../tree/master/exercises/twelve-days)
- [x] [word-count](../tree/master/exercises/word-count)

**Comment by tuxagon** [comment]
If I get a chance, I'll see what I can do with this tonight. Shouldn't take too long. It'll probably be faster to just do it manually than to script this out in consistent way.

**Comment by neganp** [comment]
I would agree. It also doesn’t have to be all at once!

**Comment by tuxagon** [comment]
@neganp So, I'm plowing through and there is definitely inconsistencies, so your review will be very handy. One such that I encountered could arguably go 2 different ways. 

The `grade-school` exercise defines some aliases for primitive types. My gut says to remove the aliases for the stub, but that does make the type signature harder to read. Aliases are strictly a readability language feature, so how we deal with them makes this where it could go either way. The pros of leaving the aliases include that it would make the types easier for newbies.

What are your thoughts on this? Should we provide aliases for types, when appropriate, in stubs? Appropriate here meaning the example uses them.

**Comment by neganp** [comment]
I would agree on avoiding the point free style. I don't have anything against it, but as Exercism is a beginner-intermediate resource I think it's appropriate to avoid it here.

I also agree with defining the aliases in `grade-school` the way you did. I think it's idiomatic Elm to have descriptive type aliases, so showing that off at least once is appropriate for an intermediate level exercise.

**Comment by tuxagon** [comment]
Thanks for the feedback! It's a good thing we are discussing these things before we have way more exercises implemented. Understanding where the line between consistency and personality is getting clearer, which should make reviews a more straightforward process for future contributors.

**Comment by neganp** [comment]
Right on. :slightly_smiling_face: 

For the record, when I asked in the Elm slack there was some objection to the idea that defining type aliases is *always* a good idea (it can make for more confusing error messages, and obfuscate the behaviour of your data types). So this is by no means the Rule of How Things Should Be Done :tm:, just a useful think to know about that we should be sure to demonstrate at some point in the track. We can leave the discussions of when it's appropriate to use in another forum.

**Comment by tuxagon** [comment]
I agree with that. It's definitely a case-by-case usage and I bet we would find a lot of people to agree with "don't use them all the time", but in specific use cases we could find as many opinions as elm offers type choices 😅 

For each exercise, we'll have to just keep in mind "Is this use of types good for someone new to elm?". If we can arrive on a consensus about the type usage, then that'll be good. I think the most important piece is getting that type signature to be appropriate for the particular exercise.

**Comment by churchie317** [comment]
Was out of the country for the last few weeks and am catching up on things that got backlogged. My two cents for what their worth:

1. Agree that we should avoid point free functions where possible as this could be a source of confusion for beginners. Maybe once #202 gets some ❤️ we can talk about making some of the advanced exercises point free.

2. This is just my opinion but I'm not sure being dogmatic about type aliases creates much value for those doing the exercises. While I personally don't disagree with the creation of the `type alias`es in the `grade-school` exercise, I wonder if users shouldn't be allowed to come to those conclusions on their own.

**Comment by tuxagon** [comment]
>  I wonder if users shouldn't be allowed to come to those conclusions on their own.

This is the reason I could see both arguments for keeping them vs removing them from the stub.  Ultimately it doesn't change anything except readability; yet it forces a certain approach. Finding that sweet spot or a specific approach will be handy. If we want to remove all aliases, I'm cool with doing that. If we keep 'em, that's probably fine too.
