### ISSUE TITLE
"Twelve Days" exercise seems out-of-place early on

### ISSUE THREAD

**Issue by mrattner** [exercism/elm#212]
The difficulty of the TwelveDays exercise seems out of proportion with the subsequent several exercises. It is only the second exercise after Hello World, yet presents quite a challenge to a learner who doesn't want to use the most naive solution (hard-coding all of the lyrics of each verse). As someone completely new to Elm, I took a couple of hours to figure out how to solve this exercise in a way I was satisfied with.

It's a great exercise, but more tricky in a functional language than other languages. I suggest increasing its difficulty rating from 1 to 3, to make Elm's exercise sequence more in line with other functional language tracks. For example, in [Haskell's track](http://exercism.io/languages/haskell/exercises), it appears as the 22nd exercise. On further inspection of haskell/config.json, I see that Twelve Days has difficulty 3 in that track.

**Comment by tuxagon** [comment]
Hi @mrattner, thank you for the suggestion! That seems reasonable. The difficulty can be sometimes hard to gauge and requires suggestions like these occasionally. I'm going to mark it as a good first issue.
