### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by tuxagon** [exercism/elm#229]
Since 0.19 came out, we should update this track to use the latest and greatest elm

**Comment by adeel41** [comment]
joined elm track today and found elm-package does not work.

**Comment by tuxagon** [comment]
@adeel41 it should, but you need to install a previous version of elm.
```bash
npm i -g elm@0.18.0
```
I am working on updating this to 0.19, but I've recently had some tragic life events occur, so I haven't gotten a chance to really do the conversion entirely yet.

**Comment by adeel41** [comment]
Sorry to hear about that but thanks for your tip to work with previous version.
