### ISSUE TITLE
elm-test doesn't run  #elm-track

### ISSUE THREAD

**Issue by CBedzz** [exercism/elm#238]
Currently, following the instructions to install elm and elm test are:
```npm install elm elm-test -g```

Unfortunately, this installs elm 0.19.0 and elm-test 0.18.13-beta3, and when you try to run ```elm-test``` in a project directory, it fails with:
```It looks like you're running elm-test from within your tests directory.```

```Please run elm-test from your project's root directory, where its elm-package.json lives!```

To remedy this for now, I got tests to work with ```npm install elm-test@beta -g```

**Comment by tuxagon** [comment]
@CBedzz a PR was merged 2 weeks ago to account for this https://github.com/exercism/elm/pull/237

Did you see this inconsistency on the website or the README?

**Comment by janmakar1** [comment]
Hello, I tried today to install elm, according to instruction on exercism website [https://exercism.io/tracks/elm/installation](url),
`
npm install -g elm@elm0.19.0 elm-test@elm0.19.0
`

but it seems it failed. Here is my output from terminal:

```
xx@yy:~/exercism/elm/hello-world$ sudo npm install -g elm@elm0.19.0 elm-test@elm0.19.0


npm WARN deprecated fsevents@1.2.4: Way too old
/usr/bin/elm -> /usr/lib/node_modules/elm/bin/elm
/usr/bin/elm-test -> /usr/lib/node_modules/elm-test/bin/elm-test

> elm@0.19.0-no-deps install /usr/lib/node_modules/elm
> node install.js

-- ERROR -----------------------------------------------------------------------

I had some trouble writing file to disk. It is saying:

Error: EACCES: permission denied, open '/usr/lib/node_modules/elm/bin/elm'

NOTE: You can avoid npm entirely by downloading directly from:
https://github.com/elm/compiler/releases/download/0.19.0/binary-for-linux-64-bit.gz
All this package does is download that file and put it somewhere.

--------------------------------------------------------------------------------

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/elm-test/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/elm-test/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.0-no-deps install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm@0.19.0-no-deps install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xx/.npm/_logs/2019-08-30T02_25_32_041Z-debug.log
```

My OS is Xubuntu 18.06, node version v12.9.1, 6.10.2. Probably, it is a problem with elm installer, not exercism issue? Is there any workaround?

**Comment by guygastineau** [comment]
@janmakar1 

I find it preferrable to set global installs for `npm` at the user level. [Instructions](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md).

I am just using a newer version of `elm-test`, but it doesn't like that the tests directory is a source directory in a source directory, so I am making a `src/` dir and moving my solution there then I am adding `src` and `tests` to the json and removing `"."`.  Might be good to know if that problem crops up for you after getting the other stuff to work.

**Comment by mpizenberg** [comment]
Hi everyone, this issue has shifted a bit since its creation. The latest issue from @guygastineau is related to the move to elm 0.19.1. I'm currently doing a bit of cleaning and updating for this. It should take roughly 2 weekends I hope.

Regarding the EACCES error from @janmakar1, as mentionned the link in @guygastineau answer, this is an NPM permission issue. The appropriate solution will be to add a link to https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally in the installation instructions. That will be done as part of the update process to 0.19.1 of the track.

I'll make a meta issue about that during the day, listing the work. Any help in the update process is welcomed. Closing this now since it's gonna be dealt with during update.

**Comment by mpizenberg** [comment]
Done in f868f59 and 701be91
