### ISSUE TITLE
elm-test not found - cannot install 

### ISSUE THREAD

**Issue by senorsmile** [exercism/elm#246]
I'm trying to get past the hello world of the elm exercism.  

I have installed elm v0.19 on my linux box using the directy binary installed.  However, it doesn't come with an elm-test. 

I found something called elm-test here: 
https://github.com/elm-explorations/test

It requires something called npm (part of nodejs).  

I installed nodejs and now have npm.  

npm install elm-test fails on one of its dependencies: 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elmi-to-json@0.19.1 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elmi-to-json@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Am I even on the right track here?  Do I report an issue on elmi-to-json to report my issue?  Are other elm v0.19 users having this same issue?

**Comment by tuxagon** [comment]
Hi @senorsmile, there are a lot of things that could be going wrong here. I found https://github.com/stoeffel/elmi-to-json/issues/20 but I don't know if that really is providing any value. I actually would recommend following the installation entirely via npm

```
$ npm install -g elm@elm0.19.0 elm-test@elm0.19.0
```

**Comment by senorsmile** [comment]
I tried that but got the same error: 
```
$ sudo npm install -g elm@elm0.19.0 elm-test@elm0.19.0
```

```
/usr/bin/elm-test -> /usr/lib/node_modules/elm-test/bin/elm-test
/usr/bin/elm -> /usr/lib/node_modules/elm/bin/elm

> elmi-to-json@0.19.1 install /usr/lib/node_modules/elm-test/node_modules/elmi-to-json
> binwrap-install

ERR Error extracting https://github.com/stoeffel/elmi-to-json/releases/download/0.19.1/elmi-to-json-0.19.1-linux.tar.gz - Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/elm-test/node_modules/elmi-to-json/unpacked_bin'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/elm-test/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elmi-to-json@0.19.1 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elmi-to-json@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by tuxagon** [comment]
On the error line
```
ERR Error extracting https://github.com/stoeffel/elmi-to-json/releases/download/0.19.1/elmi-to-json-0.19.1-linux.tar.gz - Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/elm-test/node_modules/elmi-to-json/unpacked_bin'
```
there is an
```
 Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/elm-test/node_modules/elmi-to-json/unpacked_bin'
```

You're encountering an issue due to file permissions with `binwrap-install` despite the use of `sudo`. It is actually a common issue with npm and I wish that it was made easier to reason about, but it's highly discouraged to use `sudo` with node or npm due to the likelihood that you will encounter harder to solve file permissions down the road.

Here is a doc that should help you resolve this issue.

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by senorsmile** [comment]
nvm is exactly what I needed.  That should be required as part of the installation instructions (especially for those of us who are not a part of the JS community).
