### ISSUE TITLE
Grains exercise: Add tests for second condition.

### ISSUE THREAD

**Issue by MatsLanGoH** [exercism/elm#255]
## Problem
(**This probably makes for an easy first issue.** )

The exercise requires a solution to pass the following two conditions:

	Write code that shows:

	- [x] how many grains were on a given square, and
	- [ ] the total number of grains on the chessboard

However, the included test code only checks for the first part of the solution.

## Suggestion

Add the following bits to the `grains` exercise.

- [ ] Add stub code for the `total` function.
- [ ] Add [test code](https://github.com/exercism/elm/blob/2f1ca175263bed54d4bd73a7e193df996df14003/exercises/grains/tests/Tests.elm
) for the "total number of grains" part of the solution

  - for example:

  ```Elm
        [ describe "total"
            [ test "of 1" <|
                \() -> Expect.equal (Just 1) (total 1)
            , 
                test "of 2" <|
                    \() -> Expect.equal (Just 3) (total 2)
  ```

**Comment by tuxagon** [comment]
@MatsLanGoH Thanks for the issue. I've updated the labels.

**Comment by MatsLanGoH** [comment]
I went ahead and made some additions to the exercise :)
Could someone review #256 in their spare time?

**Comment by mpizenberg** [comment]
Closing this since all concerns are discussed in associated PR
