### ISSUE TITLE
Duplicate Exercises showing for Isogram and Binary Search

### ISSUE THREAD

**Issue by paulfioravanti** [exercism/elm#258]
I'm not sure whether here is the correct place to report this, but currently on the Exercism Elm track, I'm seeing duplicates for the Isogram and Binary Search exercises:

<img width="558" alt="Elm_Track___Exercism" src="https://user-images.githubusercontent.com/543366/63384062-71740e80-c3e1-11e9-8ef4-2ef5baa86bd4.png">
<img width="576" alt="Elm_Track___Exercism" src="https://user-images.githubusercontent.com/543366/63384021-57d2c700-c3e1-11e9-8a4a-433f03868ea4.png">

The detail pages for each of the duplicates are blank, and the download links would seem to be incorrect, with each containing an ID:

<img width="602" alt="Elm___Binary_Search___Exercism" src="https://user-images.githubusercontent.com/543366/63384271-d6c7ff80-c3e1-11e9-8a42-146fe4e4131b.png">
<img width="618" alt="Elm___Isogram___Exercism" src="https://user-images.githubusercontent.com/543366/63384277-dc254a00-c3e1-11e9-8104-c405e74680d6.png">

I can confirm that this issue is at least not also occurring on the Ruby or Elixir tracks, so it would seem to be limited to just the Elm track.

**Comment by tuxagon** [comment]
Whoa, that's strange! I have a suspicion about the cause. How long ago did you complete those elm exercises? I _think_ those might be different versions of the exercise. You might've completed those exercises with a previous version of the exercise. I would also create a GitHub issue for the website at https://github.com/exercism/website

**Comment by paulfioravanti** [comment]
I completed Isogram on 31 July 2019, and Binary Search on 15 August 2019, and completed other exercises before, between, and after those dates. So, yeah, a bit strange, indeed!

The Exercism website doesn't seem to accept issues, so I'll ping the Exercism account on Twitter with a link to this issue.

**Comment by iHiD** [comment]
I think this was caused by this [commit](https://github.com/exercism/elm/commit/68282ce82466b86fa6bb82da9963b9c15369f8fa). I recently hard synced the db to the config.json as I noticed that this track was out of sync. It seems that that commit was the cause of being out of sync. I'm not on my laptop for most of the day but will check more when I am.

For future reference, exercism/exercism is the main issues repo, but opening here was fine too :)

**Comment by iHiD** [comment]
This should be fixed by https://github.com/exercism/elm/pull/259

**Comment by paulfioravanti** [comment]
Confirmed fixed! Thanks so much, @iHiD!

**Comment by iHiD** [comment]
Great. Thanks! :)
