### ISSUE TITLE
"Grade School" exercise missing test coverage

### ISSUE THREAD

**Issue by SiriusStarr** [exercism/elm#283]
The only test for `allStudents` happens to push students in reverse alphabetical order (resulting in an alphabetical order list if they are simply cons'ed on) and thus does not check that grade lists are returned sorted (unlike the `studentsInGrade` test).

```
test "get all students in the school" <|
            \() ->
                Expect.equal [ ( 3, [ "Kyle" ] ), ( 4, [ "Christopher", "Jennifer" ] ), ( 6, [ "Kareem" ] ) ]
                    (GradeSchool.empty
                        |> addStudent 4 "Jennifer"
                        |> addStudent 6 "Kareem"
                        |> addStudent 4 "Christopher"
                        |> addStudent 3 "Kyle"
                        |> allStudents
                    )
```

Presumably a third student in grade 4 should be added to ensure that sorting occurs.  I can open a PR if it's agreed that this is a problem.

**Comment by mpizenberg** [comment]
I've just looked at the canonical exercises provided there: https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json.

There seems to be a one-to-one relation with the elm tests except for the canonical test "Student names with grades are displayed in the same sorted roster" that is more or less associated with the one "get all students in the school" you mention.

I believe that non usage of `cons` could be checked with the previous simpler test "get students in a grade" by inverting Franklin and Bradley. We should also replace that mismatched test with the associated one in the cannonical tests that uses 7 people. If you feel like doing those two changes go ahead!

**Comment by SiriusStarr** [comment]
@mpizenberg The problem with using the previous test is that it only checks `studentsInGrade`; it does not check `allStudents`.  I had a mentee write a `studentsInGrade` that returned sorted results and an `allStudents` that did not (since there is no guarantee that one will be [or indeed should be] implemented in terms of the other).

Updating to the canonical test however fixes the coverage issue, so I did that.  PR #284 up.

**Comment by mpizenberg** [comment]
Ah I see. PR looks good! Thank you!
