### ISSUE TITLE
Adjust parameter and variable naming in Sum of Multiples exercise

### ISSUE THREAD

**Issue by michaelkpfeifer** [exercism/elm#285]
Naming the first parameter of the `sumOfMultiples` function `multiples` can be a little bit misleading. It should be renamed to `divisors`. What is passed into `sumOfMultiples` is a list of *divisors* of the numbers to be added.
````elm
sumOfMultiples : List Int -> Int -> Int
sumOfMultiples multiples limit =
    Debug.todo "Please implement this function"
````
This also affects `sumOfMultiples.example.elm` in a similar way.
If this is worth to be changed, I can provide a PR.

**Comment by mpizenberg** [comment]
The name `multiples` seems wrong indeed. PR is welcomed!
