### ISSUE TITLE
Skip "simulate prog 2/bearing" test in Robot Simulator exercise

### ISSUE THREAD

**Issue by michaelkpfeifer** [exercism/elm#288]
Two tests of the test suite for the Robot Simulator exercise are *not* skipped. 

The first one is the "init/coordinates" test (currently starting on line 16 of  `robot-simulator/tests/Tests.elm`) that  helps people getting started.

The second one is the "simulate prog 2/bearing" test (currently starting on line 132).

For consistency reasons (almost everything else is skipped) and to help people getting started more easily, the "simulate prog 2/bearing" test should be skipped.

If this is worth to be changed, I can provide a (very small) PR.

**Comment by mpizenberg** [comment]
Nice catch, consistency is a good thing so PR is welcome!
