### ISSUE TITLE
Update tests of Word Count exercise

### ISSUE THREAD

**Issue by michaelkpfeifer** [exercism/elm#293]
The README of the Word Count exercise states that a word will be (e.g.) a contraction of two simple words joined by a single apostrophe (ie "it's" or "they're")

However, there is no test that takes care of this special property of words.

If the tests for the Word Count exercise can be generated from data given in https://github.com/exercism/problem-specifications/blob/master/exercises/word-count/canonical-data.json, then maybe they should be regenerated. Otherwise, I can provide a PR with updated tests.

Furthermore, the example solution in `exercises/word-count/src/WordCount.example.elm` needs to be adjusted since it fails for some of the updated tests. If needed, I can include the solution I just submitted in a PR.

**Comment by mpizenberg** [comment]
I'm not aware of a way to generate tests from canonical data for the elm track. PR is welcomed with missing tests from canonical data and an update of the code therefore. By the way, would be nice to remove the regex dependency in that exercise.

Regarding auto generation of test codes from canonical data, I see that the python track have something of the sort: https://github.com/exercism/python/blob/master/bin/generate_tests.py. I guess it could be useful for this track too if that's something you're interested in trying.

**Comment by michaelkpfeifer** [comment]
PR follows.

I'll try to understand how tests are generated in the Python track.
