### ISSUE TITLE
Recruiting additional maintainers for Elm

### ISSUE THREAD

**Issue by kytrinyx** [exercism/elm#295]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by mpizenberg** [comment]
Hi, I've been maintaining the track for the past few months. I am currently under high pressure until end of February but trying to put the few hours I can with @ceddlyburge for the research experiment. Regular 3hrs/week seem thus complicated on my own but I'm more than happy to show around and mentor new maintainers for the track. I've also setup an issue https://github.com/exercism/elm/issues/280 specifically for discussions about v3 for the elm track.

**Comment by ceddlyburge** [comment]
Hi There, I'm happy to help, the only caveat I would make is that I have been mentoring on Exercism  (and am currently helping with the research experiment), and I don't have time to do more than one of these things. 

I have written some elm blog posts

- https://www.freecodecamp.org/news/scaling-elm-views-with-master-view-types/
- https://www.freecodecamp.org/news/how-to-use-netlify-functions-in-elm/
- https://codeburst.io/how-to-make-an-elm-app-progressive-d2e17d2f6fea
- https://codeburst.io/using-elm-in-react-from-the-ground-up-e3866bb0369d

And have some Elm hobby projects, one of which is active

- https://github.com/ceddlyburge/elm-league-tables-from-google-sheets
- https://github.com/ceddlyburge/hunted
- https://github.com/ceddlyburge/elm-collections

ceddlyburge is my exercism handle.

**Comment by tuxagon** [comment]
I'd like to continue being a maintainer; I've just been really busy at work and life with a new child on the way. I cannot commit to 2-3 hrs/week at this point unfortunately 😞

**Comment by ceddlyburge** [comment]
I think that the more of us there are the less each of us has to do :)
