### ISSUE TITLE
Add analyzer issues for concepts where we can't check concept usage with tests

### ISSUE THREAD

**Issue by mpizenberg** [exercism/elm#387]

**Comment by leojpod** [comment]
Could elm-review help with that? like write a special rule that require to use a certain things (e.g. use `case ... of` instead of `if then else if then else ... `)

**Comment by mpizenberg** [comment]
elm-review could definitely help with analyzers! I haven't explored that space yet though and never written a rule yet either. But if you think of something for existing exercises don't hesitate to ask around in the elm-review channel of the slack.

**Comment by mpizenberg** [comment]
One thing for sure, is that we can't blindly apply elm-review rules on all exercises. Especially in concept exercises where some concepts might not be introduced yet, or push the code in a direction that may not be the most idiomatic one (that's also a sign that a concept exercise is not designed too well but we do how we can ^^)

**Comment by leojpod** [comment]
I was more thinking of rules designed explicitly for one exercise, not of rules to apply to all exercises. 
I don't have much time to play with it right now but I'll keep it in mind :)

**Comment by jiegillet** [comment]
[I have opened issues](https://github.com/exercism/elm-analyzer/issues) for all the concept exercises. Hopefully that can be part of the workflow when adding new ones.
