### ISSUE TITLE
Add link to icons in the helper doc to create a concept exercise

### ISSUE THREAD

**Issue by mpizenberg** [exercism/elm#411]
The icons live here: https://github.com/exercism/website-icons/tree/main/exercises

**Comment by ValeriaD23** [comment]
Hello,

Can you elaborate a bit about what the question is here please?

Thanks in advance

**Comment by mpizenberg** [comment]
To be honest, I don't remember what I meant XD. Only that it had to do with this document I wrote when I was still spending time creating concept exercises: https://github.com/exercism/elm/blob/main/docs/contributing-concept.md

**Comment by pwadsworth** [comment]
@mpizenberg I think this issue can be closed now. c2b00fa added the icons.

**Comment by mpizenberg** [comment]
Right! thanks @pwadsworth
