### ISSUE TITLE
Concept: set

### ISSUE THREAD

**Issue by mpizenberg** [exercism/elm#424]
# Design

## Learning objectives

- Know about the `Set` data structure.
- Know how to create an empty set.
- Know how to add elements to a set.
- Know how to remove elements to a set.
- Know how to convert sets to and from lists.
- Know how to check if an element is part of a set.
- Know how to combine multiple sets.
- Know how to filter and partition a set.

## Out of scope

- Nothing is really out of scope.

## Concepts

- set

## Prerequisites

- comparison

**Comment by jiegillet** [comment]
I had a random idea for a suitable exercise so I'm putting it here as a suggestion: `gotta-catchem-all`, an exercise where you collect trading cards and try to have the full collection.

You can start a new collection (empty set), get new cards but your collection doesn't improve for cards you already have, remove one to give to your little sister, combine collection with your best friend, select the shiny cards...

**Comment by jiegillet** [comment]
Another random idea, we have the possibility of introducing two concepts in one exercise, so I was thinking we could introduce comparisons #423 together with this one, since sets need to be ordered.

**Comment by ceddlyburge** [comment]
Hi @jiegillet , this issue is done now I think?

**Comment by jiegillet** [comment]
No, I ended up doing separate exercises. I have already written the `about.md` for sets, maybe I'll open a draft PR
