### ISSUE TITLE
Overflow issue in the UI

### ISSUE THREAD

**Issue by 552020** [exercism/elm#474]
On the right bar in the results tab of https://exercism.org/tracks/elm/exercises/largest-series-product

![image](https://user-images.githubusercontent.com/60273337/159881572-96618b83-ce46-4daf-8010-3d7f430b688f.png)

**Comment by mpizenberg** [comment]
Thanks for your feedback on this and on the previous issue @552020 ! I haven't had the chance to look at it yet but I'll have time next week!
