### ISSUE TITLE
Wording on Luigi's luscious lasagna

### ISSUE THREAD

**Issue by alvaro121** [exercism/elm#492]
Hello,
At Luigi's luscious lasagna's [problem description](https://github.com/exercism/elm/blob/b9c2e8db9849c15e9ecf614245a706af1aae10f8/exercises/concept/luigis-luscious-lasagna/.docs/instructions.md) it says (bolded by me)

> Define the `preparationTimeInMinutes` **constant** (in the let part of the let expression) that takes the number of layers you added to the lasagna as **a parameter** and [...]

The example shows that it should actually be a function, so I think saying to define it as a constant (a constant function?) is confusing. I have seen some community solutions and they seem to be split at defining it as a constant or a function.

Likewise, it says

> Define the `remainingTimeInMinutes` function (**in the in part of the let expression**) that takes two parameters [...]

But I don't think you can define the function in the `in` part of the let expression, but instead the function's body is a let expression whose `in` part is the final calculation.

**Comment by ceddlyburge** [comment]
Hi there. This is a good point, we will have a think.

The Elm syntax itself doesn't include constants, but people often call functions with zero parameters 'constants' (especially ones where the return value is just a single value, like in `expectedMinutesInOven`), which is why it gets confusing I think. Maybe we should just call them all functions.

I think the second point is a bit easier, maybe "Define the remainingTimeInMinutes *calculation* (in the in part of the let expression) that takes two parameters [...]"?

**Comment by ceddlyburge** [comment]
How about something like this?

> Define the remainingTimeInMinutes function that takes two parameters and has a let expression as its body. The first parameter is the number of layers you added to the lasagna, and the second parameter is the number of minutes since you starting cooking. 
> 
> Define expectedMinutesInOven (in the let part of the let expression) to check how many minutes the lasagna should be in the oven. According to the cooking book, the expected oven time in minutes is 40:
> 
> ...
> 
> Define preparationTimeInMinutes (in the let part of the let expression) that takes the number of layers you added to the lasagna as a parameter and returns how many minutes you spent preparing the lasagna, assuming each layer takes you 2 minutes to prepare.
> 
> ...
> 
> Return how many minutes are left until the lasagna is finished (in the in part of the let expression), which is the sum of the preparationTimeInMinutes and the expectedMinutesInOven minus the number of minutes since you starting cooking.
>

**Comment by ceddlyburge** [comment]
Hi There, I'm not sure the const / function thing is explained anywhere. The fact that functions have no parameters mean that a constant and a zero parameter function are defined using the same syntax, and retrieved using the same syntax. The fact that values are immutable means that there
