### ISSUE TITLE
The Lasagna exercise is duplicated

### ISSUE THREAD

**Issue by MatthijsBlom** [exercism/elm#497]
Witness: [search on "lasagna"](https://exercism.org/tracks/elm/exercises?criteria=lasagna).

Not necessarily a problem &ndash; especially as their foci are actually different &ndash; but the extremely similar names did confuse me.

**Comment by ceddlyburge** [comment]
Hi Matthijs, thanks for the feedback.

As you mention this isn't a bug as such, but is still confusing. I think we should probably rename these a bit to make them more distinct.

Do you have any suggestions?

Cheers, Cedd

**Comment by MatthijsBlom** [comment]
I do not at present.

There is some talk right now about creating a concept exercise about `let` and `where` for the Haskell track. If that exercise happens, I imagine it could easily be adopted by the Elm track as well.

**Comment by ceddlyburge** [comment]
Hmm, we already have the exercise for 'let', it might be easier for the haskell track to adopt this one.

I'll think of a new name ...
