### ISSUE TITLE
Elm logo

### ISSUE THREAD

**Issue by copying** [exercism/elm#499]
I was reading the "Elm icon" section of your README. The logo is actually just a tangram in the square configuration ([Wikipedia's tangram arcticle](https://en.wikipedia.org/wiki/Tangram)). In fact when you haver the "Playground" on the official webpage, it makes a figure (a solution of the game). I used to play with it when I was little, so thinking about it made me smile :)

**Comment by ceddlyburge** [comment]
Hi Marti, thanks for the interesting comment. Do you think it makes sense to update the readme with this information?
Cheers, Cedd

**Comment by copying** [comment]
Hey, sorry for the delay.

I'm not sure what you should do with this information. It was a case of reading the readme and thinking that it was not right. Also, I'm not a lawyer but it seems to me that if this is so old, using it isn't fair use because it shouldn't fall under copyright.

Cheers

**Comment by ceddlyburge** [comment]
Ok,so it sounds like we can just remove the copy, and just use the logo, as it doesn't have any copyright restrictions. Thanks for the tip :)

**Comment by ceddlyburge** [comment]
Hi Marti, I've opened a pull request for this change, please feel free to take a look and return comments.
Thanks, Cedd
