### ISSUE TITLE
Concept: Strings

### ISSUE THREAD

**Issue by jiegillet** [exercism/elm#536]
# Design

## Goal

The Goal is to learn to use the `String` and `Char` modules.

## Learning objectives

Students should be able to
- insert unicode characters in strings
- verify `Char` properties (`isAlpha`, `isUpper`...)
- use basic string functions (`length`, `replace`...)
- split and join strings (`split`, `words`, `lines`, `(++)`, `concat`, `join`...)
- cut up strings (`slice`, `left`...)
- check for substrings (`contains`, `startsWith`...)
- convert to and from other types (`fromInt`, `toInt`...)
- format a string (`toUpper`, `toLower`, `trim`...)
- use some higher order functions (`all`, `any`, `filter`...)

## Out of scope

- Nothing in particular, although there is probably too much to cover in details

## Concepts

The concept this exercise unlocks is:

- `strings`

## Prerequisites

- booleans
- maybe
- lists

## Analyzer

TBD depending on the exercise

**Comment by pwadsworth** [comment]
Seems no one is working on this. If that is the case, I am open to take a stab at it.

**Comment by ceddlyburge** [comment]
Hi Pete, that would be great, thanks!

**Comment by pwadsworth** [comment]
Is the concept already written? If so, I would like to see it to make the exercise match its main topics. If not, I will write the concept as well.

**Comment by mpizenberg** [comment]
I don't think we wrote anything yet. Are you familiar already with exercism repository structure?

**Comment by pwadsworth** [comment]
Yes. I checked the concepts directory. There is no strings concept there.
