### ISSUE TITLE
Concept: JSON Decoders

### ISSUE THREAD

**Issue by jiegillet** [exercism/elm#538]
# Design

## Goal

The Goal is to learn to use the `Json.Decode` and `Json.Encode` modules.

## Learning objectives

Students should be able to
- encode any JSON `Value` (`Json.Encode.object`, `list` and other primitives)
- prettify a value (`encode`)
- understand why decoders are useful even though the concept is unusual
- decode JSON primitives (`bool`, `int`, `string`...)
- decode data structures (`list`, `dict`, `nullable`)
- decode objects (`field`, `at`)
- deal with uncertainty (`maybe`, `oneOf`)
- modify and chain decoders (`map`, `andThen`, `succeed`)
- test a decoder on a string input (`decodeString`)

## Out of scope

- encoder aliases (`array`, `set`)
- more niche decoders (`array`, `keyValuePairs`, `oneOrMore`, `index`, `null`, `value`)
- dealing with `Error` and `fail`
- decoding recursive structures (`lazy`, a quick mention is fine)

## Concepts

The concept this exercise unlocks is:

- `json`

## Prerequisites

- strings
- lists
- dict
- records
- maybe
- custom-types (?)

## Analyzer

TBD depending on the exercise

-----------

### Comments

- Would be nice to implement [`rest-api`](https://github.com/exercism/problem-specifications/blob/main/exercises/rest-api/description.md) first to have one practice exercise
- link: https://guide.elm-lang.org/effects/json.html

**Comment by ceddlyburge** [comment]
I think the api concept is still good, its just that it is complicated, and the instructions are not as clear as they might be (especially for Elm I think).

Maybe we could jump on a call sometime and discuss how to make it clear what the student is supposed to do?

**Comment by jiegillet** [comment]
Oh I still intend to keep `rest-api`, and I don't think having a difficult exercise is inherently a problem (I love those as a student), I'm just looking for another one that could help practicing decoders.

**Comment by ceddlyburge** [comment]
Hmmm, none of those look that good. Maybe we could create a new exercise. Json encoding / decoding is something that people do find confusing when starting Elm, so it is a good idea. Maybe encoding a request to the github api (which is well known), and decoding a response?

**Comment by jiegillet** [comment]
Creating a proper new practice exercise is way more work than I'm willing to do! 
I guess we'll need a really good concept exercise :)

**Comment by mpizenberg** [comment]
> Maybe encoding a request to the github api (which is well known), and decoding a response?

Good idea to work on a concrete real-life thing. We'd have to rebuild the JS `Value` ourselves directly in the test though as obviously there is no outside world access in tests file.
