### ISSUE TITLE
bettys-bike-shop tests do not actually verify type signature

### ISSUE THREAD

**Issue by softmoth** [exercism/elm#590]
There are a number of solutions to the bettys-bike-shop exercise which contain:

```elm
penceToPounds : Float -> Float
```

This should be caught by the tests, perhaps by explicitly typing the argument passed to the function.

**Comment by ceddlyburge** [comment]
Thanks for reporting this Tim.

I've created a pull request for the fix
https://github.com/exercism/elm/pull/592

Cheers, Cedd
