### ISSUE TITLE
Wrong type mentioned in the description of step 4 of the learning exercise Secure Treasure Chest

### ISSUE THREAD

**Issue by rjpgt** [exercism/elm#593]
Step 4 of the exercise description:

This function should take two parameters, and have a type definition.

a String (for the password)
a TreasureChest generic custom type

Shouldn't TreasureChest be SecureTreasureChest ?

**Comment by ceddlyburge** [comment]
Good spot jagapoga! I've created a pull request which you can review if you would like.
https://github.com/exercism/elm/pull/594

You are welcome to create pull requests yourself by the way.

Cheers, Cedd
