### ISSUE TITLE
Small correction in the introduction in the learning exercise Magician in Training

### ISSUE THREAD

**Issue by rjpgt** [exercism/elm#597]
...
An element in an Array is retrieved using Array.get:

```
sixSeven = Array.fromList [ 6, 7 ] 
Array.get 0 sixSeven --> 6
```
6 in the second line should be `Just 6`

**Comment by ceddlyburge** [comment]
Thanks for the feedback jagapoga.

I've created this PR to fix this, please feel free to review it
https://github.com/exercism/elm/pull/599

Cheers, Cedd
