### ISSUE TITLE
Update strain test

### ISSUE THREAD

**Issue by BNAndras** [exercism/elm#600]
I'd like to update the strain tests. There are two canonical tests missing for lists, and I'd like to update the existing tests to use the canonical data. I've got a PR ready, but the README indicates I should open an issue first. :)

**Comment by ceddlyburge** [comment]
Thanks Andras. Opening issues first seemed a bit weird to me at first too, but actually I mostly like it now. It gives everyone a chance to discuss things before doing the work, which can be useful to stop going down a blind alley. Probably overkill in this case though!

Anyway, if there are canonical tests from the problem-specifications repo missing, then a PR to add the missing tests sounds great, thanks :)
