### ISSUE TITLE
Concept Exercise for Strings

### ISSUE THREAD

**Issue by pwadsworth** [exercism/elm#606]
## Develop concept exercise(s) to practice the Strings concept covering the following topics:
1. Insert unicode characters in strings
2. Verify Char properties (isAlpha, isUpper...)
3. Use basic string functions (length, replace...)
4. Split and join strings (split, words, lines, (++), concat, join...)
5. Cut up strings (slice, left...)
6. Check for substrings (contains, startsWith...)
7. Convert to and from other types (fromInt, toInt...)
8. Format a string (toUpper, toLower, trim...)
9. Use some higher order functions (all, any, filter...)

## Recommendations:
- [99-Beers][beers]: Covers 1, 3, 4 (partial), and 7 above.
- [Squeaky Clean][squeaky]: Covers 1, 2, 3, 4, 5, 6, and 8 above

[squeaky]: https://github.com/exercism/csharp/blob/main/exercises/concept/squeaky-clean/.docs/instructions.md
[beers]: http://inventwithpython.com/pythongently/exercise23/

**Comment by jiegillet** [comment]
There is one last thing we should do on this issue before closing: go through existing practice exercises and add the "strings" concept to the relevant ones ("prerequisites" field for concept exercises and "prerequisites"/"practices" for practice exercises). 
We already have the (obsolete) "topics" on the exercises, which sometimes contains "strings" already. That should help.

**Comment by pwadsworth** [comment]
> There is one last thing we should do on this issue before closing: go through existing practice exercises and add the "strings" concept to the relevant ones ("prerequisites" field for concept exercises and "prerequisites"/"practices" for practice exercises). We already have the (obsolete) "topics" on the exercises, which sometimes contains "strings". That should help.

I'll tackle this over the next week.

**Comment by jiegillet** [comment]
Closed via #629
