### ISSUE TITLE
Implement new pop-count

### ISSUE THREAD

**Issue by BNAndras** [exercism/elm#615]
I'd like to port this exercise introduced in exercism/problem-specifications#2333.

**Comment by ceddlyburge** [comment]
That would be great, thanks Andras :)

Do you want any pointers before you start?

This is a recent PR from a new contributor. Its for a concept exercise, which are slightly different to a practice exercises, but it might be useful to look at.
https://github.com/exercism/elm/pull/611

**Comment by BNAndras** [comment]
Thanks. I’ve ported this exercise for five tracks now so I’ll need to “Elm”ify my approach including making the test runner happy.
