### ISSUE TITLE
Windowing System [JS] misguiding instruction for Task 5

### ISSUE THREAD

**Issue by rahuljindal1** [exercism/elm#701]
While exercising Windowing System [JS], Task 5 [ Add a method to move the window ], I noticed that the instructions are not clear as to what need to be done. Along with that, the example given in the instruction part is incomplete as well.

The instruction state that `The maximum position in either direction depends on the current size of the window`, but this is not the case, while running the tests, I noticed that it is the combination of both current position and size of the window also.

Then in the example: `if the window's size is at x = 250, y = 100 and a move to x = 600, y = 200 is requested, then the window would be moved to x = 550, y = 200 as the screen is not large enough in the x direction to fully accommodate the request.`, the window's size is in terms of position while it should have been in height and width and current position should have been part of the example as well. Same can be seen from the tests.

```
const programWindow = new ProgramWindow();
const newSize = new Size(100, 100);
programWindow.resize(newSize);
const newPosition = new Position(750, 650);
programWindow.move(newPosition);
expect(programWindow.position.x).toBe(700);
expect(programWindow.position.y).toBe(500);
```

**Issue Exercise URL:** https://exercism.org/tracks/javascript/exercises/windowing-system/edit

**Comment by jiegillet** [comment]
Hi @rahuljindal1 I think you're on the wrong repo, you're probably looking for https://github.com/exercism/javascript
I will close your issue.
