### ISSUE TITLE
Bad formatting for `Maze Maker` exercise

### ISSUE THREAD

**Issue by anshulvv** [exercism/elm#717]
Bad formatting for the instructions sections of `Maze Maker` exercise.
Can be seen on the exercise's online editor.
https://exercism.org/tracks/elm/exercises/maze-maker/edit

<img width="503" alt="image" src="https://github.com/user-attachments/assets/69b53667-7e46-484b-a541-d0a410e71cd4">

**Comment by mpizenberg** [comment]
Hum, I’m wondering if this is an issue in the viewer. I can’t find a source that would have line ending at this location.

**Comment by jiegillet** [comment]
Definitely an issue with the viewer. The source for the instructions is this:

https://github.com/exercism/elm/blob/58981673582af2f7b8655f466a05d05aeb6e3626/exercises/concept/maze-maker/.docs/instructions.md?plain=1#L51-L53

The viewer is interpreting the minus sign in `n - 1` to be the first item of a list.
I have no idea how the viewer could be fixed, we could try the workaround of removing spaces in `n-1`?

**Comment by anshulvv** [comment]
This line here in `complex numbers` exercise is similar (inline code with ` - `):
https://github.com/exercism/elm/blob/58981673582af2f7b8655f466a05d05aeb6e3626/exercises/practice/complex-numbers/.docs/instructions.md?plain=1#L6
But it's formatting is correct in edit view
<img width="501" alt="image" src="https://github.com/user-attachments/assets/a3f5312e-b5db-4a24-9ef9-0d2dff87904c">

So, it's weird behavior.

@jiegillet's suggestion seem potential solution for now.

**Comment by ceddlyburge** [comment]
Maybe the `n - 1` is being confused with `\n - 1` which would be a bulleted list.

In which case we could use a different symbol instead of `n`.

We could also try and escape the `-`?

Markdown [supports that](https://www.markdownguide.org/basic-syntax/#escaping-characters), so it would work in theory ...

**Comment by jiegillet** [comment]
I doubt it thinks it's a `\n` because the `n` is rendered.
Escaping the `-` is my new favorite potential solution. let's try that!

**Comment by ceddlyburge** [comment]
Ok, I'm happy to try that. I should have time tomorrow.

**Comment by jiegillet** [comment]
This issue was closed automatically when we merged the PR,  but I actually never checked that it worked.
It worked :)

<img width="478" alt="Screenshot 2024-10-23 at 21 38 04" src="https://github.com/user-attachments/assets/c6705f8c-cea3-4852-a118-3a5253fb3851">
